[2025-03-25]
+ 4Bit Unpacking for doppler
+ TODO BLANKING
+ report 02c4 sea_clutter is to big (4 bytes)


[2025-03-26]
+ Scan Speed can only be changed on transmit.
-- Have a delay before recording to be sur that scan_speed is good.
-- Save Raw data with a small header containing the import report values.
+ input value between 0-255 as int instead of 0-100. Avoid cumulative rounding/truncating error.
+ finish report with the proper values.
+ add exception for (doppler, mode, nudge)
+ Target Expansion register seems to differ between G4-G3(0x12) and Halo(0x09)
-- On G4 only on or off






UBUNTU INSTALL
### for pin control
>> sudo apt install python3-lgpio
>> pip install lgpio # instead of gpiozero


## Enable ssh
>> sudo apt update
>> sudo apt install apache2 (is it necessary ?)

>> sudo apt install openssh-server
>> sudo systemctl enable ssh
>> sudo systemctl start ssh

### Disable to disable Desktop:
>> sudo systemctl set-default multi-user.target
>> sudo reboot

### to remove every desktop related packages
>> sudo apt purge ubuntu-desktop
>> sudo apt autoremove


### to have service on start
>> install ifupdown
# bash startup service

### move the radar_startup.service to /etc/systemd/system/
>> sudo systemctl daemon-reload
>> sudo systemctl enable radar_startup.service
>> sudo systemctl start radar_startup.service


### ERROR MOUNTING DISK ON UBUNTU
>> sudo fdisk -l
>> sudo apt install nfs-common
>> sudo apt install cifs-utils
>> sudo ntfsfix -d /dev/sdb1

### OK maybe just need to edit this tab
>> sudo nano -Bw /etc/fstab
```

LABEL=writable  /       ext4    discard 0       1
LABEL=system-boot       /boot/firmware  vfat    defaults        0       1
/dev/disk/by-id/usb-Seagate_Portable_NAA5PW6Y-0:0-part1 /media/capteur/2To auto nosuid,nodev,nofail,x-gvfs-show 0 0
```


### Disable usb,wifi,eth

>> sudo nano /boot/config.txt
```
dtoverlay=disable-wifi
dtoverlay=disable-bt

```
>> sudo reboot
>> sudo apt install hub-ctrl
>> hub-ctrl -h 0 -P 1 -p 0



### BUG TO FIX

#### 1

(2025-04-08 11:50:20,308) - {MainThread} - [INFO]     - Next scan time: 2025-04-08T11:51:00
(2025-04-08 11:50:20,324) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:22,325) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:24,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:26,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:28,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:30,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:32,327) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:34,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:36,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:38,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:40,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:42,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:44,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:46,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:48,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:50,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:52,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:54,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:56,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:50:58,326) - {report}   - [WARNING]  - report b'\x11\xc6' unknown
(2025-04-08 11:51:00,002) - {MainThread} - [INFO]     - Scan Time: 2025-04-08T11:51:00
Exception in thread Scan Watchdog:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/capteur/program/piradar/piradar/scripts/script_utils.py", line 355, in duty
    raise NavicoRadarError("Scan delay timeout.")
piradar.scripts.script_utils.NavicoRadarError: Scan delay timeout.
(2025-04-08 11:51:00,031) - {MainThread} - [INFO]     - Tx On commands sent
(2025-04-08 11:51:00,088) - {report}   - [WARNING]  - report b'\t\xc4' unknown

####

Other error

(2025-04-16 13:32:03,062) - {data}     - [ERROR]    - Error Raise when trying to process data: unpack_from requires a buffer of at least 1 bytes for unpacking 1 bytes at offset 0 (actual buffer size is 0)


###

(2025-04-16 14:03:11,069) - {MainThread} - [ERROR]    - sea_state was not set. Expected: calm, Actual: moderate
(2025-04-16 14:03:11,070) - {MainThread} - [ERROR]    - target_expansion was not set. Expected: off, Actual: high
(2025-04-16 14:03:11,070) - {MainThread} - [ERROR]    - target_separation was not set. Expected: off, Actual: low


